FROM php:8.2-cli-alpine3.21

# Встановлення залежностей
RUN set -ex && \
    apk add --no-cache \
        mariadb-client \
        nodejs \
        npm \
        git \
        libzip-dev \
        linux-headers \
        freetype-dev \
        libpng-dev \
        libjpeg-turbo-dev \
        redis \
        && \
    apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        build-base \
        && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-configure zip && \
    docker-php-ext-install \
        pdo \
        pdo_mysql \
        sockets \
        zip \
        gd \
        exif && \
    pecl install redis xdebug && \
    docker-php-ext-enable redis xdebug && \
    apk del .build-deps && \
    rm -rf /var/cache/apk/* /tmp/pear

# Додаємо Composer
COPY --from=composer:2.8.5 /usr/bin/composer /usr/bin/composer
ENV PATH="${PATH}:/var/www/vendor/bin"

# Налаштування Xdebug
RUN echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.start_with_request=no" >> /usr/local/etc/php/conf.d/xdebug.ini

# Встановлення Corepack і Yarn
RUN npm install -g corepack && corepack enable && corepack prepare yarn@4.6.0 --activate

WORKDIR /var/www
